#!/usr/bin/env python3
"""
Run CodeAgent with improved ReAct Loop

Tests the enhanced CodeAgent featuring:
- True ReAct (Reason-Act-Observe) loop
- LLM-powered reasoning about next actions
- Comprehensive answer generation
- Goal-based completion logic
- Per-file metrics tracking
"""
import sys
from pathlib import Path
sys.path.insert(0, '.')

from cf.configs.config_mgr import ConfigManager
from cf.agents.code import CodeAgent

def main():
    import argparse
    parser = argparse.ArgumentParser(
        description="Run CodeAgent with improved ReAct loop",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s . "How does the SupervisorAgent orchestrate agents?"
  %(prog)s /path/to/repo "Explain the routing system"
  %(prog)s . "What is the tool registry?" --verbose
        """
    )
    parser.add_argument('repo_path', help='Repository path to analyze')
    parser.add_argument('question', help='Question to ask')
    parser.add_argument('--verbose', '-v', action='store_true',
                       help='Show detailed ReAct phases (Reason-Act-Observe)')
    parser.add_argument('--show-metrics', '-m', action='store_true',
                       help='Show detailed per-file metrics')
    args = parser.parse_args()

    print('=' * 80)
    print('🤖 CodeAgent with Improved ReAct Loop')
    print('=' * 80)
    print(f'📁 Repository: {args.repo_path}')
    print(f'❓ Question: {args.question}')
    if args.verbose:
        print('🔍 Verbose mode: Enabled (will show Reason-Act-Observe phases)')
    print('=' * 80)
    print()
    
    # Setup
    config_mgr = ConfigManager('cf/configs/config.yaml')
    config = config_mgr.get_config()

    # Enable verbose logging if requested
    if args.verbose:
        config.setdefault('logging', {})['verbose'] = True

    print('🚀 Starting CodeAgent ReAct analysis...\n')

    # Create and run CodeAgent with improved ReAct loop
    import time
    start_time = time.time()
    agent = CodeAgent(args.repo_path, config)
    result = agent.analyze(args.question)
    total_time = time.time() - start_time

    print('\n' + '=' * 80)
    print('📊 ANALYSIS COMPLETE - Results Summary')
    print('=' * 80)
    print(f'⏱️  Total Time: {total_time:.2f}s')
    print(f'✅ Success: {result.get("success", False)}')
    print(f'📈 Confidence: {result.get("confidence", 0):.1%}')
    print(f'🔄 ReAct Iterations: {result.get("iterations", 0)}/{config.get("agents", {}).get("max_iterations", 10)}')
    print(f'💡 Insights Gathered: {len(result.get("insights", []))}')
    print(f'🛠️  Tools Used: {result.get("tools_used", 0)}')
    print(f'📞 Function Calls: {result.get("function_calls_made", 0)}')
    print(f'📄 Files Analyzed: {result.get("files_analyzed", 0)}')
    
    # Print the comprehensive narrative generated by LLM synthesis
    if result.get('success') and result.get('narrative'):
        print('\n' + '=' * 80)
        print('📖 COMPREHENSIVE NARRATIVE (LLM Synthesized)')
        print('=' * 80)
        print(result['narrative'])
        print('=' * 80)
    else:
        if not result.get('success'):
            print(f'\n❌ Error: {result.get("error", "Unknown error")}')

    # Print key insights with confidence scores
    if result.get('insights'):
        print(f'\n💡 KEY INSIGHTS (Top {min(5, len(result["insights"]))} of {len(result["insights"])}):')
        print('-' * 80)
        for i, insight in enumerate(result['insights'][:5], 1):
            content = insight.get('content', 'No content')
            confidence = insight.get('confidence', 0)
            source = insight.get('source', 'unknown')
            print(f'{i}. [{confidence:.0%}] {content}')
            if args.verbose:
                print(f'   Source: {source}')
    
    # Print file summaries if available (only in verbose or show-metrics mode)
    if (args.verbose or args.show_metrics) and hasattr(agent, 'file_summaries') and agent.file_summaries:
        print(f'\n📄 ANALYZED FILES ({len(agent.file_summaries)} files):')
        print('-' * 80)
        for idx, (file_path, summary) in enumerate(list(agent.file_summaries.items())[:5], 1):
            print(f'\n{idx}. 🗂️  {file_path}')
            print(f'   Purpose: {summary.get("purpose", "No purpose")}')
            print(f'   Overview: {summary.get("overview", "No overview")[:100]}...' if len(summary.get("overview", "")) > 100 else f'   Overview: {summary.get("overview", "No overview")}')

            # Handle classes (could be list of strings or list of dicts)
            classes = summary.get('classes', [])
            if classes:
                try:
                    classes_slice = classes[:3] if isinstance(classes, list) else []
                    if classes_slice and isinstance(classes_slice[0], dict):
                        class_names = [c.get('name', str(c)) for c in classes_slice]
                        print(f'   Classes: {", ".join(class_names)}')
                    elif classes_slice and isinstance(classes_slice[0], str):
                        print(f'   Classes: {", ".join(classes_slice)}')
                    elif isinstance(classes, str):
                        print(f'   Classes: {classes}')
                except (IndexError, TypeError):
                    print(f'   Classes: {str(classes)[:100]}')

            # Handle functions (could be list of strings or list of dicts)
            functions = summary.get('functions', [])
            if functions:
                try:
                    functions_slice = functions[:3] if isinstance(functions, list) else []
                    if functions_slice and isinstance(functions_slice[0], dict):
                        func_names = [f.get('name', str(f)) for f in functions_slice]
                        print(f'   Functions: {", ".join(func_names)}')
                    elif functions_slice and isinstance(functions_slice[0], str):
                        print(f'   Functions: {", ".join(functions_slice)}')
                    elif isinstance(functions, str):
                        print(f'   Functions: {functions}')
                except (IndexError, TypeError):
                    print(f'   Functions: {str(functions)[:100]}')

            print(f'   Complexity: {summary.get("complexity", "unknown")}')

            # Show architectural insights if available
            if summary.get('architectural_insights'):
                insights = summary['architectural_insights']
                if insights != 'LLM analysis failed - manual review needed':
                    print(f'   🏗️  Architecture: {insights[:150]}...' if len(insights) > 150 else f'   🏗️  Architecture: {insights}')

        if len(agent.file_summaries) > 5:
            print(f'\n   ... and {len(agent.file_summaries) - 5} more files')
    
    # Show detailed metrics (only if --show-metrics flag is used)
    if args.show_metrics and hasattr(agent, 'file_analysis_metrics') and agent.file_analysis_metrics:
        total_tokens = sum(m["total_tokens"] for m in agent.file_analysis_metrics)
        total_time = sum(m["total_duration_ms"] for m in agent.file_analysis_metrics)
        total_files = len(agent.file_analysis_metrics)
        successful_files = len([m for m in agent.file_analysis_metrics if m['success']])

        # Show file processing breakdown
        discovered_files = len(getattr(agent, 'discovered_files', []))

        print(f'\n🎯 DETAILED PERFORMANCE METRICS:')
        print('-' * 80)
        print(f'📂 Files discovered: {discovered_files}')
        print(f'📄 Files processed: {total_files}')
        print(f'✅ Files successfully analyzed: {successful_files}')
        print(f'🎯 Total tokens: {total_tokens:,}')
        print(f'⏱️  Total processing time: {total_time/1000:.1f}s')
        print(f'📈 Average tokens per file: {total_tokens/successful_files:.0f}' if successful_files > 0 else '📈 Average tokens per file: 0')
        print(f'⚡ Average time per file: {total_time/successful_files/1000:.1f}s' if successful_files > 0 else '⚡ Average time per file: 0s')

        # Show token breakdown
        total_prompt = sum(m["prompt_tokens"] for m in agent.file_analysis_metrics)
        total_completion = sum(m["completion_tokens"] for m in agent.file_analysis_metrics)
        print(f'💭 Token breakdown: {total_prompt:,} prompt → {total_completion:,} completion')

        # Show per-file metrics breakdown (top 5 slowest/largest)
        print(f'\n📊 Top 5 files by processing time:')
        sorted_by_time = sorted(agent.file_analysis_metrics, key=lambda x: x['total_duration_ms'], reverse=True)
        for i, m in enumerate(sorted_by_time[:5], 1):
            print(f'   {i}. {m["file_path"]}: {m["total_duration_ms"]/1000:.2f}s ({m["total_tokens"]} tokens)')

    # Final summary
    print('\n' + '=' * 80)
    print('✅ CodeAgent ReAct Analysis Complete!')
    print('=' * 80)
    print(f'\n💡 Tip: Use --verbose to see ReAct phases (Reason-Act-Observe)')
    print(f'💡 Tip: Use --show-metrics for detailed performance metrics\n')

if __name__ == '__main__':
    main()
